# Generated by Django 3.0.4 on 2020-04-30 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trajet',
            new_name='Trip',
        ),
        migrations.RenameField(
            model_name='localisations',
            old_name='trajet',
            new_name='trip',
        ),
    ]
