# Generated by Django 3.0.5 on 2020-05-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20200501_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
    ]
