# Generated by Django 3.0.5 on 2020-05-02 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200501_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='feeling',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
