# Generated by Django 3.0.5 on 2020-05-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200502_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='front.Category'),
        ),
    ]
